kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      analytics : true

analytics:
  provider: google
  google: 
      tracking_id : 'UA-75321534-2'
